config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'h8' => 'pages#h8'
  get 'pages/home'
  get 'pages/transactions'
  get 'pages/new_transaction'
  get 'transactions' => 'pages#transactions'
  resources :withdrawals
  resources :deposits

end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
  validates :amount, presence: true

  before_create :round

  private def round
    self.amount = self.amount.round(2)
  end

  def self.array
    self.all.each.map{|x| x.amount.to_f}
  end

  def self.total
    self.all.reduce(0){|sum, x| sum + x.amount.to_f}
  end

  def this_month?
    (self.this_year?) && (self.created_at.strftime("%m").to_i == Time.now.strftime("%m").to_i)
  end

  def this_year?
    self.created_at.strftime("%Y") == Time.now.strftime("%Y")
  end

  def last_month?
    self.created_at.strftime("%m").to_i == (Time.now - 1.month).strftime("%m").to_i
  end

  def day
    self.created_at.strftime("%e")
  end

  def less_than_a_month_ago?
    (self.this_year?) && ((self.this_month?) || (self.last_month? && (self.day) > Time.now.strftime("%e")))
  end
end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
  validates :amount, presence: true

  before_create :round

  private def round
    self.amount = self.amount.round(2)
  end

  def self.array
    self.all.each.map{|x| x.amount.to_f}
  end

  def self.total
    self.all.reduce(0){|sum, x| sum + x.amount.to_f}
  end

  def this_month?
    self.created_at.strftime("%m").to_i == Time.now.strftime("%m").to_i
  end

  def this_year?
    self.created_at.strftime("%Y") == Time.now.strftime("%Y")
  end

  def last_month?
    self.created_at.strftime("%m").to_i == (Time.now - 1.month).strftime("%m").to_i
  end

  def day
    self.created_at.strftime("%e")
  end

  def less_than_a_month_ago?
    (self.this_year?) && ((self.this_month?) || (self.last_month? && (self.day) > Time.now.strftime("%e")))
  end

  def self.biggest_this_month
    withdrawals = self.order(:amount).reverse
    biggest = Withdrawal.new(amount: 0)
    withdrawals.each do |withdrawal|
      if withdrawal.this_month?
        biggest = withdrawal
        break
      end
    end
    biggest.amount
  end

  def self.biggest
    self.order(:amount).last.amount
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy]

  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = Deposit.all
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show
  end

  # GET /deposits/new
  def new
    @deposit = Deposit.new
  end

  # GET /deposits/1/edit
  def edit
  end

  # POST /deposits
  # POST /deposits.json
  def create
    @deposit = Deposit.new(deposit_params)

    respond_to do |format|
      if @deposit.save
        format.html { redirect_to @deposit, notice: 'Deposit was successfully created.' }
        format.json { render :show, status: :created, location: @deposit }
      else
        format.html { render :new }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposits/1
  # PATCH/PUT /deposits/1.json
  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'Deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits/1
  # DELETE /deposits/1.json
  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'Deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposit
      @deposit = Deposit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposit_params
      params.require(:deposit).permit(:amount)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @deposits = Deposit.all
    @withdrawals = Withdrawal.all
  end

  def transactions
    @deposits = Deposit.all
    @withdrawals = Withdrawal.all
  end

  def new_transaction
  end

  def h8
  end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController
  before_action :set_withdrawal, only: [:show, :edit, :update, :destroy]

  # GET /withdrawals
  # GET /withdrawals.json
  def index
    @withdrawals = Withdrawal.all
  end

  # GET /withdrawals/1
  # GET /withdrawals/1.json
  def show
  end

  # GET /withdrawals/new
  def new
    @withdrawal = Withdrawal.new
  end

  # GET /withdrawals/1/edit
  def edit
  end

  # POST /withdrawals
  # POST /withdrawals.json
  def create
    @withdrawal = Withdrawal.new(withdrawal_params)

    respond_to do |format|
      if @withdrawal.save
        format.html { redirect_to @withdrawal, notice: 'Withdrawal was successfully created.' }
        format.json { render :show, status: :created, location: @withdrawal }
      else
        format.html { render :new }
        format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /withdrawals/1
  # PATCH/PUT /withdrawals/1.json
  def update
    respond_to do |format|
      if @withdrawal.update(withdrawal_params)
        format.html { redirect_to @withdrawal, notice: 'Withdrawal was successfully updated.' }
        format.json { render :show, status: :ok, location: @withdrawal }
      else
        format.html { render :edit }
        format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /withdrawals/1
  # DELETE /withdrawals/1.json
  def destroy
    @withdrawal.destroy
    respond_to do |format|
      format.html { redirect_to withdrawals_url, notice: 'Withdrawal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_withdrawal
      @withdrawal = Withdrawal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def withdrawal_params
      params.require(:withdrawal).permit(:amount, :recipient)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/withdrawals_helper.rb
module WithdrawalsHelper
end

app/views/deposits/_form.html.erb
<%= form_for(@deposit) do |f| %>
  <% if @deposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposit.errors.count, "error") %> prohibited this deposit from being saved:</h2>

      <ul>
      <% @deposit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form' %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deposits</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= deposit.amount %></td>
        <td><%= link_to 'Show', deposit %></td>
        <td><%= link_to 'Edit', edit_deposit_path(deposit) %></td>
        <td><%= link_to 'Destroy', deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposit', new_deposit_path %>

app/views/deposits/new.html.erb
<h1>New Deposit</h1>

<%= render 'form' %>

<%= link_to 'Back', deposits_path %>

app/views/deposits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @deposit.amount %>
</p>

<%= link_to 'Edit', edit_deposit_path(@deposit) %> |
<%= link_to 'Back', deposits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_deposit_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deposits</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= deposit.amount %></td>
        <td><%= link_to 'Show', deposit %></td>
        <td><%= link_to 'Edit', edit_deposit_path(deposit) %></td>
        <td><%= link_to 'Destroy', deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposit', new_deposit_path %>

app/views/pages/_withdrawal_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Withdrawals</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @withdrawals.each do |withdrawal| %>
      <tr>
        <td><%= withdrawal.amount %></td>
        <td><%= withdrawal.recipient %></td>
        <td><%= link_to 'Show', withdrawal %></td>
        <td><%= link_to 'Edit', edit_withdrawal_path(withdrawal) %></td>
        <td><%= link_to 'Destroy', withdrawal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Withdrawal', new_withdrawal_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Soon will display </p>
<ul>
  <li><strike>the total amount of money in his/her account (this should be a method which is tested!)</strike></li>
  <li><strike>a link to the list of transactions</strike></li>
  <li><strike>a link to create a new transaction</strike></li>
  <li><strike>The total amount spent in the current calendar month</strike></li>
  <li><strike>The total amount spent in the prior calendar month</strike></li>
  <li><strike>The total number of transactions in the current calendar month</strike></li>
  <li><strike>The total number of transactions in the prior calendar month</strike></li>
  <li><strike>The biggest expense in the current calendar month</strike></li>
  <li>The biggest expense ever</li>
  <li>The name of the place/person where you have spent the most money (over all time)</li>
</ul

<p>
  Total: <%= Deposit.total - Withdrawal.total %>
</p>

<%= link_to "Transactions", pages_transactions_path %>
<%= link_to "New Transaction", pages_new_transaction_path %>

<h3>Withdrawals in current calendar month</h3>
<% @withdrawals.each do |withdrawal| %>
  <% if withdrawal.this_year? && withdrawal.this_month? %>
    <p><%= withdrawal.amount %></p>
  <% end %>
<% end %>

<h3>Withdrawals in previous month</h3>
<% @withdrawals.each do |withdrawal| %>
  <% if withdrawal.this_year? && withdrawal.last_month? %>
    <p><%= withdrawal.amount %></p>
  <% end %>
<% end %>

<!-- <h3>Withdrawals last month</h3>
<% @withdrawals.each do |withdrawal| %>
  <% if withdrawal.less_than_a_month_ago? %>
    <p><%= withdrawal.amount %></p>
  <% end %>
<% end %> -->

<h3>Transactions this month</h3>
<% depo_count = @deposits.reduce(0) { |sum, deposit| deposit.this_month? ? sum+1 : sum+0 } %>
<% with_count = @withdrawals.reduce(0) { |sum, withdrawal| withdrawal.this_month? ? sum+1 : sum+0 } %>
<%= depo_count + with_count %>

<h3>Transactions last month</h3>
<% depo_count = @deposits.reduce(0) { |sum, deposit| deposit.last_month? ? sum+1 : sum+0 } %>
<% with_count = @withdrawals.reduce(0) { |sum, withdrawal| withdrawal.last_month? ? sum+1 : sum+0 } %>
<%= depo_count + with_count %>

<h3>Biggest transaction this month</h3>
<%= Withdrawal.biggest_this_month %>

<h3>Biggest transaction ever</h3>
<%= Withdrawal.biggest %>

<br/>
<br/>

<%= link_to "H8 if you dare", h8_path %>

app/views/pages/new_transaction.html.erb
<h1>Pages#new_transaction</h1>
<p>Find me in app/views/pages/new_transaction.html.erb</p>

app/views/pages/transactions.html.erb
<h1>Transactions</h1>
<p>Account Summary</p>
<%= render "deposit_index" %>
<%= render "withdrawal_index" %>

app/views/withdrawals/_form.html.erb
<%= form_for(@withdrawal) do |f| %>
  <% if @withdrawal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@withdrawal.errors.count, "error") %> prohibited this withdrawal from being saved:</h2>

      <ul>
      <% @withdrawal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :recipient %><br>
    <%= f.text_field :recipient %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/withdrawals/edit.html.erb
<h1>Editing Withdrawal</h1>

<%= render 'form' %>

<%= link_to 'Show', @withdrawal %> |
<%= link_to 'Back', withdrawals_path %>

app/views/withdrawals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Withdrawals</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @withdrawals.each do |withdrawal| %>
      <tr>
        <td><%= withdrawal.amount %></td>
        <td><%= withdrawal.recipient %></td>
        <td><%= link_to 'Show', withdrawal %></td>
        <td><%= link_to 'Edit', edit_withdrawal_path(withdrawal) %></td>
        <td><%= link_to 'Destroy', withdrawal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Withdrawal', new_withdrawal_path %>

app/views/withdrawals/new.html.erb
<h1>New Withdrawal</h1>

<%= render 'form' %>

<%= link_to 'Back', withdrawals_path %>

app/views/withdrawals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @withdrawal.amount %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @withdrawal.recipient %>
</p>

<%= link_to 'Edit', edit_withdrawal_path(@withdrawal) %> |
<%= link_to 'Back', withdrawals_path %>